# Generated by Django 2.0.4 on 2019-04-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_devrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devrequest',
            name='dev',
        ),
        migrations.AddField(
            model_name='devrequest',
            name='developers',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
