# Generated by Django 2.0.4 on 2019-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20190111_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='projecttitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
