# Generated by Django 2.0.4 on 2019-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_question_codesample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='score',
            field=models.IntegerField(),
        ),
    ]
