# Generated by Django 2.0.4 on 2019-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_randomquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquiz',
            name='questions',
            field=models.CharField(max_length=400),
        ),
    ]
