# Generated by Django 2.0.4 on 2019-03-14 11:56

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20190314_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquiz',
            name='questions',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=150),
        ),
    ]
