# Generated by Django 2.0.4 on 2019-03-15 09:34

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20190314_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomquiz',
            name='correctanswers',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True),
        ),
    ]
