# Generated by Django 2.0.4 on 2019-03-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_randomquiz_correctanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomquiz',
            name='correctanswers',
        ),
    ]
